[package]
published-at = ""

name = "suipass"
version = "0.0.4"
edition = "2024.beta"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }

[addresses]
suipass = "0x0"

[dev-dependencies]

[dev-addresses]
